DROP TABLE users;
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL UNIQUE,
    password TEXT, -- Allows longer hashed passwords
    history '' -- Stores command history as JSON (map structure)
);


CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL UNIQUE,
    password TEXT, -- Allows longer hashed passwords
    history TEXT -- Stores command history as JSON (map structure)
);
